### ISSUE TITLE
Proxy parse cert from header SSL_CLIENT_CERT always failed (nginx and apache)

### ISSUE THREAD

**Issue by dakeduke** [xipki/commons#2]
https://github.com/xipki/commons/blob/d5af531688cda83a174e8ed936cb7dd130317af4/security/src/main/java/org/xipki/security/util/X509Util.java#L149-L153

BC `PremReader` `readPemObject` always returns NULL for both *Nginx* and *Apache2*   
The parser does not seems to support tabulation nor space.

https://github.com/xipki/commons/blob/d5af531688cda83a174e8ed936cb7dd130317af4/security/src/main/java/org/xipki/security/util/TlsHelper.java#L112

*Nginx* with `$ssl_client_cert` send the certificate with `\n` and `\t`.  
During the process `\n` are discarded but `\t` are still present  
Fix example: `clientCert = X509Util.parseCert(StringUtil.toUtf8Bytes(pemClientCert.replace("\t", "\n")));`

Note: `$ssl_client_raw_cert`  can't be used otherwise *tomcat* complain about header which does not respect the RFC (It's probably right I didn't check)

*Apache2* send the certificate with space (`\n` replaced by 0x20)  

So it's probably better to clean HTTP header `SSL_CLIENT_CERT`, remove all space characters, remove BEGIN/END delimiter  
base64 decode and then parse the DER.

Off-topic:  When the cert can't be parsed EST (at least) returns HTTP 500, I would expect HTTP 400 (or HTTP 4XX)
if the client send garbage to the server

**Comment by xipki** [comment]
Thank you for the report.
1. For nginx, $ssl_client_cert is deprecated. I will change the README to use $ssl_client_escaped_cert instead.
2. Could you please uploaded the raw header data of SSL_CLIENT_CERT? To keep the special symbols, please write the result to a file and upload the file.

**Comment by dakeduke** [comment]
[header_capture.zip](https://github.com/xipki/commons/files/13215169/header_capture.zip)
File names should be explicit  
It's a direct export from *wireshark* of the header `SSL_CLIENT_CERT`, I put apache and nginx qith `$ssl_client_cert` and `$ssl_client_escaped_cert`

BTW, thanks for Xipki, it's a nice software

EDIT: The export failed for `$ssl_client_cert`, sorry
but it's like described in my first post, the cert sent contains `\n` and `\t` (0x0A and 0x09)

```
SSL_CLIENT_CERT: -----BEGIN CERTIFICATE-----
	MIICEjCCAbigAwIBAgIQQJw3MZym/Aeh/lt27gVjQjAKBggqhkjOPQQDAjBAMQsw
	CQYDVQQGEwJERTEOMAwGA1UECgwFeGlwa2kxCzAJBgNVBAsMAkVDMRQwEgYDVQQD
	DAtUTFMgRGVtbyBDQTAeFw0xOTA1MTAwNzI0MThaFw00OTA1MTAwNzI0MThaMEAx
	CzAJBgNVBAYTAkRFMRMwEQYDVQQKDAp4aXBraSBkZW1vMQswCQYDVQQLDAJFQzEP
	MA0GA1UEAwwGY2xpZW50MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEV3VKXS4n
	CdbPS3G7CxjTVcJs9kqG9eJ2FGF7v2c1MI+zmNaKgJPa7UThuHnQEVFtXfo3EZWs
	Bb4IecEmgOm44KOBkzCBkDARBgNVHREECjAIggZjbGllbnQwDAYDVR0TAQH/BAIw
	ADAfBgNVHSMEGDAWgBRj2wt6eIyr/TsDUsiIuES+nSyQuTAdBgNVHQ4EFgQUk8Kj
	MFE64rG+i0okai08RA2Y+6UwDgYDVR0PAQH/BAQDAgbAMB0GA1UdJQQWMBQGCCsG
	AQUFBwMBBggrBgEFBQcDAjAKBggqhkjOPQQDAgNIADBFAiEAwuiirkeLk+ZmueYJ
	4x0BJkvfFRrsED8jKqs7J0WsAZYCIATpd5RJ8n6T6GSpcVi4IlkI4ekK2zcPoDyv
	NBdmZD90
	-----END CERTIFICATE-----
```
